### ISSUE TITLE
Include abacusutils

### ISSUE THREAD

**Issue by adematti** [cosmodesi/cosmodesiconda#1]
Following up with @seshnadathur one should try to include abacusutils into cosmodesiconda.
@lgarrison, do you think abacusutils would rather fit as:
i) a ~ stable package, updates on a ~ trimester basis
ii) a package with more regular updates, that can be module loaded/unloaded (as e.g. desihub packages)?
As a side note, I see it has a number of hard requirements in setup.py; are all those required by the core package? (e.g. I think schwimmbad, emcee, are only required by scripts/). We probably want to have them in cosmodesiconda anyway, but maybe should be listed as "extras"?

**Comment by lgarrison** [comment]
Hi @adematti, this sounds like a good idea, I'm happy to help.

abacusutils is still undergoing fairly regular updates; some of it is new functionality, and some is bugfixes. The core module to read the halo catalogs is pretty stable, but the HOD module is being more actively developed. So I think it would be best to find a solution that would allow users to ~immediately update abacusutils if we find a bug and publish a new minor version. Would that be something like option (ii)? I'm actually not very familiar with the DESI software stack.

I'm happy to work on reducing the dependency footprint of the code.  I agree, it can probably be factorized into core dependencies and "extras". I'll take a look.

**Comment by adematti** [comment]
Yes, that sounds like option (ii): if the end-user wants to switch to another version, that would be as simple as:
module unload abacusutils
module load abacusutils/newversion
On the developer side, it's just updating the list of packages to install, https://github.com/cosmodesi/cosmodesiconda/blob/main/cosmodesimodules/pkg_list.txt and run cosmodesimodules/install.sh.
Great! I'll work on having this in cosmodesiconda, then!

**Comment by adematti** [comment]
closing as it was solved in f1c689304871992f23129fe26a28d8e0db1def1a
